/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLStTwitterElement extends HTMLStencilElement {
    'hashtag': string;
    'list': string;
    'text': string;
    'type': string;
    'user': string;
  }
  var HTMLStTwitterElement: {
    prototype: HTMLStTwitterElement;
    new (): HTMLStTwitterElement;
  };
  interface HTMLElementTagNameMap {
    'st-twitter': HTMLStTwitterElement;
  }
  interface ElementTagNameMap {
    'st-twitter': HTMLStTwitterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'st-twitter': JSXElements.StTwitterAttributes;
    }
  }
  namespace JSXElements {
    export interface StTwitterAttributes extends HTMLAttributes {
      'hashtag'?: string;
      'list'?: string;
      'text'?: string;
      'type'?: string;
      'user'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
